# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra"
gem "sinatra-websocket"
gem "eventmachine"
gem "thin"
gem "sys-proctable"
gem "require_all"

group :test do
  gem "rack-test"
  gem "rspec"
  gem "pry-byebug"
  gem "irb"
  gem "rdoc"
  gem "webmock"
end

