version: '2'

volumes:
  spotifycache:
  snapcastcache:
  browsercache:

services:

  # Core services
  # -- Required for a fully featured installation of balenaSound
  # -- Mutiroom services can be removed if not using multiroom mode
  audio:
    build: ./core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    ports:
      - 4317:4317

  sound-supervisor:
    build: 
      context: .
      dockerfile: ./core/sound-supervisor/Dockerfile.template
    network_mode: host
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: 1

  multiroom-server:
    build: ./core/multiroom/server
    restart: on-failure
    volumes:
      - 'snapcastcache:/var/cache/snapcast' # Persist client names
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780


  logging:
    image: balenablocks/log2screen
    privileged: true
    restart: always
    network_mode: host
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1

  # Plugins
  airplay:
    build: ./plugins/airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

  browser:
    build: ./browser
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: host
    volumes:
      - 'browsercache:/data' # Only required if using PERSISTENT flag (see below)

  spotify:
    build: ./plugins/spotify
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify
