FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-ruby:3.1.2-buster

ENV PULSE_SERVER=tcp:localhost:4317

RUN install_packages pianobar youtube-dl ffplay

COPY start.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
