FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:14-buster

COPY start.sh /usr/src/
ADD src /usr/src
RUN rm -rf /usr/src/node_modules
WORKDIR /usr/src
RUN npm install

CMD [ "/bin/bash", "/usr/src/start.sh" ]
