FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster

ENV PULSE_SERVER=tcp:localhost:4317

RUN install_packages pianobar ffmpeg ruby python

RUN curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
RUN chmod a+rx /usr/local/bin/youtube-dl

COPY start.sh /usr/src/

CMD [ "/bin/bash", "/usr/src/start.sh" ]
